Update workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -42,6 +42,16 @@ jobs:
         with:
           terraform_version: 1.3.0
 
+      - name: Set Up AWS CLI
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+          aws configure set region $AWS_REGION
+
       - name: Terraform Init
         run: cd terraform && terraform init
 
@@ -58,20 +68,11 @@ jobs:
         run: ls -la
 
       - name: Terraform Plan
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ secrets.AWS_REGION }}
-
         run: |
           cd terraform
           terraform plan -var-file="values.tfvars" -input=false
 
       - name: Terraform Apply
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
           cd terraform
           terraform apply -var-file="values.tfvars" -auto-approve -input=false
@@ -89,9 +90,18 @@ jobs:
         run: |
           scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no -r terraform/scripts/* ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/scripts/
 
+      - name: Verify AWS CLI Configuration
+        run: |
+          aws sts get-caller-identity
+          aws s3 ls s3://storage-for-env-files/.env/
+          
+      - name: Test Download Command
+        run: |
+          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws
+
       - name: Download .env from S3
         run: |
-          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws || { echo 'Failed to download .env.aws'; exit 1; }
+          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws || { echo "Error: $?" ; exit 1; }
 
       - name: Copy.env to EC2
         run: |
