Update workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -9,7 +9,6 @@ on:
       - main
 
 jobs:
-  # Job 1: Create key
   create_key:
     runs-on: ubuntu-latest
     steps:
@@ -22,17 +21,16 @@ jobs:
           chmod 600 house_manager_new_key.pem
 
       - name: Upload SSH Key as Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: ssh_private_key
           path: house_manager_new_key.pem
 
-  # Job 2: Create EC2 instance
   create_ec2_instance:
     runs-on: ubuntu-latest
     needs: create_key
     outputs:
-      public_dns: ${{ steps.get_public_dns.outputs.public_dns }}
+      public_dns_ec2: ${{ steps.get_public_dns.outputs.PUBLIC_DNS }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -53,10 +51,10 @@ jobs:
           aws configure set region $AWS_REGION
 
       - name: Download SSH Key Artifact
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: ssh_private_key
-          path: ./  # Downloads 'house_manager_new_key.pem' to the current directory
+          path: ./
 
       - name: Fix Permissions on Private Key
         run: chmod 600 ./house_manager_new_key.pem
@@ -78,58 +76,48 @@ jobs:
         id: get_public_dns
         run: |
           cd terraform
-          echo "PUBLIC_DNS=$(terraform output -raw public_dns)" >> "$GITHUB_ENV"
+          echo "PUBLIC_DNS=$(terraform output -raw public_dns)" >> "$GITHUB_OUTPUT"
 
+#      - name: Copy Scripts to EC2
+#        run: |
+#          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no -r terraform/scripts/* ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/scripts/
+#
+#      - name: Download .env from S3
+#        run: |
+#          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws || { echo "Error: $?" ; exit 1; }
+#
+#      - name: Copy.env to EC2
+#        run: |
+#          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no .env.aws ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/envs/
+#
+#      - name: Run Scripts on EC2
+#        run: |
+#          ssh -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$PUBLIC_DNS "bash /home/ubuntu/app/scripts/setup.sh"
+
+#  # Job 3: Copy Scripts to EC2
+  copy_scripts:
+    runs-on: ubuntu-latest
+    needs: [ create_key, create_ec2_instance ]
+    steps:
+      - env:
+          PUBLIC_DNS: ${{needs.create_ec2_instance.outputs.public_dns_ec2}}
       - name: Debug Environment Variables
         run: printenv
+
+      - name: Check PUBLIC_DNS
+        run: |
+          echo "PUBLIC_DNS: $PUBLIC_DNS"
+
+      - name: Download SSH Key Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: ssh_private_key
+          path: ./  # Downloads 'house_manager_new_key.pem' to the current directory
 
       - name: Copy Scripts to EC2
         run: |
           scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no -r terraform/scripts/* ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/scripts/
 
-      - name: Verify AWS CLI Configuration
-        run: |
-          aws sts get-caller-identity
-          aws s3 ls s3://storage-for-env-files/.env/
-          
-      - name: Test Download Command
-        run: |
-          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws
-
-      - name: Download .env from S3
-        run: |
-          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws || { echo "Error: $?" ; exit 1; }
-
-      - name: Copy.env to EC2
-        run: |
-          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no .env.aws ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/envs/
-
-      - name: Run Scripts on EC2
-        run: |
-          ssh -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$PUBLIC_DNS "bash /home/ubuntu/app/scripts/setup.sh"    
-
-#  # Job 3: Copy Scripts to EC2
-#  copy_scripts:
-#    runs-on: ubuntu-latest
-#    needs: [ create_key, create_ec2_instance ]
-#    steps:
-#      - name: Debug Environment Variables
-#        run: printenv
-#
-#      - name: Check PUBLIC_DNS
-#        run: |
-#          echo "PUBLIC_DNS: $PUBLIC_DNS"
-#
-#      - name: Download SSH Key Artifact
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: ssh_private_key
-#          path: ./  # Downloads 'house_manager_new_key.pem' to the current directory
-#
-#      - name: Copy Scripts to EC2
-#        run: |
-#          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no -r terraform/scripts/* ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/scripts/
-#
 #  # Job 4: Copy .env file from S3 to EC2
 #  copy_env_file:
 #    runs-on: ubuntu-latest
